# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lambda-otel-spans
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: dev
  region: eu-west-2
  apiGateway:
    apiKeys:
      - ${self:provider.stage}-PrivateKey
    metrics: true
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  hello:
    handler: functions/hello.handler
    layers:
      - arn:aws:lambda:eu-west-2:901920570463:layer:aws-otel-nodejs-ver-0-19-0:1
    events:
      - http:
          path: /hello
          method: get
          private: true
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
